name: ReleaseBuild

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout SunEngine
      uses: actions/checkout@v2
      
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
      
    - name: Build with dotnet
      run: dotnet publish --configuration Release "Server/SunEngine.Cli" --output build/Server
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
          
    - name: npm install, install quasar, quasar build
      run: |
        cd Client
        cp -RT src/site.template src/site
        npm install
        npm -g install @quasar/cli
        npx quasar build
        cd ..
        cp -RT Client/dist/spa/. build/wwwroot
      env:
        CI: true
        
    - name: Copy Config, Resources, SunEngine.md and move all build to root
      run: |
        cp -RT Config.server.template build/Config.server.template
        cp -RT Resources build/Resources
        cp -T SunEngine.md build/SunEngine.md
        #find . -maxdepth 1 -not -name 'build' -not -name '.' -not -name '.git' -print0 | xargs -0 rm -rf
        #cp -RT build .
        #rm -rf build 
        #echo "resulted files"
        #ls -a

    - name: Checkout SunEngine
      uses: actions/checkout@v2
      with:
        repository: sunengine/SunEngine.Build
        path: BuildRepo
      
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'build'
        cwd: './BuildRepo'
        author_name: Build bot
        author_email: build@build.run
        force: true
        message: 'Auto build'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

